In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')
df = df[['Account Name', 'Investors']]
df=df.drop([2,6,14,15,16,22,23,24,26,28,29,30,31,32,33,37,38,39,40], axis=0)
df.reset_index(inplace=True, drop=True)
Investors = df.Investors

# Create long list of VCs, remove duplicates
string=''
for item in Investors:
    string += '; '+str(item)
Unique_Investor_List = sorted(list(set(string.split('; '))))[1:]

Unique_Investor_List[:5]

['#Angels', '137 Ventures', '500 Startups', '8VC', 'A-Grade Investments']

In [3]:
# Create a row for each unique VC value
df=pd.concat([df,pd.DataFrame(columns=Unique_Investor_List)]).fillna(0)
df.head()

,Account Name,Investors,#Angels,137 Ventures,500 Startups,8VC,A-Grade Investments,A.Capital Ventures,AFSquare,AOL,...,Wells Fargo,WestRiver Group,WestSummit Capital,Wildcat Venture Partners,William Hambrecht,Y Combinator,You & Mr Jones Brandtech Ventures,Yuri Sagalov,blisce/,iGlobe Partners
0,appfire,Silversmith Capital Partners,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Atlassian,Employee Stock Option Fund (ESO Fund); T. Rowe...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Code42,New Enterprise Associates (NEA); SharesPost In...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Coinbase,BBVA Ventures; Vayner/RSE; USAA; Sozo Ventures...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,Crunchbase,AOL; Cowboy Ventures; Mayfield Fund; 8VC; Feli...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
# Populate the empty VC rows
for i in range(len(Investors)): # By each company
    a_list = Investors[i].split('; ') # By each VC
    for item in a_list:
        df[item][i] = 1
df.head()

C:\Users\sski\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """

,Account Name,Investors,#Angels,137 Ventures,500 Startups,8VC,A-Grade Investments,A.Capital Ventures,AFSquare,AOL,...,Wells Fargo,WestRiver Group,WestSummit Capital,Wildcat Venture Partners,William Hambrecht,Y Combinator,You & Mr Jones Brandtech Ventures,Yuri Sagalov,blisce/,iGlobe Partners
0,appfire,Silversmith Capital Partners,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,Atlassian,Employee Stock Option Fund (ESO Fund); T. Rowe...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,Code42,New Enterprise Associates (NEA); SharesPost In...,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,Coinbase,BBVA Ventures; Vayner/RSE; USAA; Sozo Ventures...,1,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,Crunchbase,AOL; Cowboy Ventures; Mayfield Fund; 8VC; Feli...,0,0,0,1,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0

In [10]:
# Create count matrix
df_matrix = df.loc[:,Unique_Investor_List]
df_matrix.loc['Total',:]= df_matrix.sum(axis=0)
df_matrix.loc[:,'Total'] = df_matrix.sum(axis=1)
# Add back company names
df_matrix=df_matrix.reindex(columns=list(['Account Name']+ df_matrix.columns.tolist()))
df_matrix['Account Name'] = df['Account Name']
df_matrix.iloc[28,0]='All'
df_matrix.tail()

,Account Name,#Angels,137 Ventures,500 Startups,8VC,A-Grade Investments,A.Capital Ventures,AFSquare,AOL,Accel,...,WestRiver Group,WestSummit Capital,Wildcat Venture Partners,William Hambrecht,Y Combinator,You & Mr Jones Brandtech Ventures,Yuri Sagalov,blisce/,iGlobe Partners,Total
24,Upwork,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,18.0
25,Vlocity,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,8.0
26,Weebly,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9.0
27,Zuora,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,19.0
Total,All,1.0,1.0,2.0,2.0,1.0,1.0,1.0,1.0,4.0,...,1.0,1.0,1.0,1.0,4.0,1.0,1.0,1.0,1.0,432.0

In [6]:
sum_counts = list(df_matrix.loc['Total',:])[1:-1] #Pull out 2 total cell
max_index = sum_counts.index(max(sum_counts))
print("What VC invested in the P1 Equity Pledge Company list the most?",Unique_Investor_List[max_index])

What VC invested in the P1 Equity Pledge Company list the most? SV Angel

In [7]:
# Create new dataframe to filter by total counts
df_sum = pd.DataFrame(dict(zip(Unique_Investor_List,sum_counts)),index=[0])
df_sum = df_sum[df_sum > 2].dropna(axis=1)
# Print out of top VCs with more than 2 hits on the CNBC list
print(df_sum.T[0].astype(int))
# Save top VC list
df_top_VC = df_sum.T

Accel                                    4
All Blue Capital                         3
Altimeter Capital                        3
Andreessen Horowitz                      3
Bain Capital Ventures                    3
Bessemer Venture Partners                5
BlackRock                                3
Employee Stock Option Fund (ESO Fund)    3
EquityZen                                5
Felicis Ventures                         3
FundersClub                              3
G Squared                                4
GV                                       4
Goldman Sachs                            3
Greylock Partners                        4
Index Ventures                           4
Kleiner Perkins                          4
Light Street Capital                     3
Lowercase Capital                        3
SV Angel                                 9
Salesforce Ventures                      5
Sequoia Capital                          4
SharesPost Investment Management         4
Silicon Valley Bank                      3
Spark Capital                            3
T. Rowe Price                            7
Techstars                                3
Webb Investment Network                  3
Wellington Management                    7
Y Combinator                             4
Name: 0, dtype: int32

In [11]:
# Create smaller dataframe with just the top VCs
top_VC=df_sum.T[0].index.to_list()
top_cols=['Account Name']+top_VC
df_matrix_top = df[top_cols]
# Add Total columns
df_matrix_top.loc['Total',:]= df_matrix_top.sum(axis=0)
df_matrix_top.loc[:,'Total'] = df_matrix_top.sum(axis=1)
df_matrix_top.iloc[28,0]='All'
df_matrix_top

C:\Users\sski\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

,Account Name,Accel,All Blue Capital,Altimeter Capital,Andreessen Horowitz,Bain Capital Ventures,Bessemer Venture Partners,BlackRock,Employee Stock Option Fund (ESO Fund),EquityZen,...,Sequoia Capital,SharesPost Investment Management,Silicon Valley Bank,Spark Capital,T. Rowe Price,Techstars,Webb Investment Network,Wellington Management,Y Combinator,Total
0,appfire,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,Atlassian,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0
2,Code42,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
3,Coinbase,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,4.0
4,Crunchbase,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
5,DocuSign,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,5.0
6,Dropbox,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,10.0
7,Flexport,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
8,Gainsight,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
9,Lookout,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,10.0
10,MediaMath,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
11,Okta,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,6.0
12,PagerDuty,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,1.0,8.0
13,Pinterest,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,6.0
14,Pluralsight,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
15,Postmates,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0
16,Puppet,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
17,Rally Software,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
18,Salesforce,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,SendGrid,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,4.0
20,Skilljar,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0
21,Slack,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,10.0
22,Twilio,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,8.0
23,Unity Technologies,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0
24,Upwork,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,4.0
25,Vlocity,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
26,Weebly,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,4.0
27,Zuora,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,...,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,7.0
Total,All,4.0,3.0,3.0,3.0,3.0,5.0,3.0,3.0,5.0,...,4.0,4.0,3.0,3.0,7.0,3.0,3.0,7.0,4.0,119.0

In [9]:
df_top_VC.to_csv("top_VC_list.csv") # Top hit list of VCs
df_matrix_top.to_csv('top_company_matrix.csv') # Top VC company matrix
df_matrix.to_csv('company_matrix.csv') # Company matrix